SET NAMES UTF8;
DROP DATABASE IF EXISTS ch;
CREATE DATABASE ch CHARSET=UTF8;
USE ch;
CREATE TABLE ch_message(
  mid INT PRIMARY KEY AUTO_INCREMENT,
  uname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  subject VARCHAR(255),
  message VARCHAR(255) NOT NULL
);
